### ISSUE TITLE
Support caching the words list

### ISSUE THREAD

**Issue by Lunaphied** [Brian3647/seme#1]
linku.la's database isn't updated particularly frequently and we can save some request time and bandwidth usage by only downloading it if it's changed by saving a copy of the request locally and then only making a parallel request to check if we need to update the database

I'm willing to work on this

**Comment by ibnz36** [comment]
things to keep in mind:
- Following #2, the time between each time everything's cached could be changed by the user
- Choosing which words to cache - only the ones used before or everything?
- Where is everything going to be stored?

**Comment by Lunaphied** [comment]
There are (on Linux) standardized places to put a cache  `$XDG_CACHE_HOME`, on Windows I don't remember but there's also a location that's reasonable, maybe just in normal `%APPDATA%`, there should be a crate we can depend on to abstract this difference. Same for finding the config file.

Caching all the words seems to make the most sense to me since the API you're currently using just downloads all of them, just storing that file and making it either fetch from the file or the API depending on if it exists or needs to be updated should be good, anu seme?

**Comment by ibnz36** [comment]
Currently, it doesn't download all the words, it just fetches the specific word that is being searched - I was thinking about storing the words that have been requested and when asking for the same word do a check:
![Ex](https://github.com/Brian3647/seme/assets/73384214/df20a041-4705-49b4-a88b-972e4d4470f4)

**Comment by janTatesa** [comment]
I've started working on it . Will open a PR soon.

**Comment by janTatesa** [comment]
Underestimated how long it will take me. Will finish tomorrow

**Comment by ibnz36** [comment]
@TadoTheMiner no pressure - take as long as you want, this is an OSS project
thanks for contributing :3

**Comment by ibnz36** [comment]
closed by #4
